package enums;

public enum ViewEnum {
    // Start
    START,
    LOGIN,
    REGISTRATION,
    ORGANIZER,
    SPEAKER,
    VIP,
    ATTENDEE,

    // Account
    EXIT,
    LOGOUT,
    VIEW_ALL_ACCOUNTS,
    ADD_CONTACT,
    REMOVE_CONTACT,
    VIEW_CONTACTS,
    MESSAGE,
    VIEW_CONVERSATION,
    VIEW_EVENT_SCHEDULE,
    DOWNLOAD_SCHEDULE,
    VIEW_MENU,
    INVALID,
    VOID,

    // Organizer
    NEW_SPEAKER,
    MESSAGE_ALL_SPEAKERS,
    MESSAGE_ALL_ATTENDEES,
    VIEW_ROOMS,
    ADD_ROOM,
    ADD_EVENT,
    CANCEL_EVENT,
    RESCHEDULE_EVENT,

    // Speaker
    MESSAGE_TALK_ATTENDEES,
    VIEW_SPEAKER_SCHEDULE,

    // Attendee,
    VIEW_SIGNUP_SCHEDULE,
    SIGNUP_EVENT,
    LEAVE_EVENT,
}
